name: Auto PR Creation Caller

on:
  push:
    branches:
      - main

jobs:
  call_auto_pr_workflow:
    uses: rdkcentral/build_tools_workflows/.github/workflows/auto_pr_creation_manifest.yml@RDKEMW-4778
    secrets:
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
