name: Auto PR Creation Caller

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  debug_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered"
      
  call_auto_pr_workflow:
    #secrets:
      #RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
    uses: .github/workflows/auto_pr_creation_meta.yml@topic/test-4778
    secrets:
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
    #runs-on: ubuntu-latest
    #steps:
     # - name: Print placeholder instead of actual logic
     #   run: echo "This is a placeholder for the actual logic."
