on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]
    branches:
      - develop
jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate version in PR description
        run: |
          PR_DESC="${{ github.event.pull_request.body }}"
          VERSION_FROM_PR=$(echo "$PR_DESC" | grep -oiP 'version\s*:\s*\K[0-9]+\.[0-9]+\.[0-9]+(?=)' || true)
          TOP_TAG=$(grep -m 1 -oP '^#### \[\K[^\]]+' CHANGELOG.md)
          if [[ -z "$VERSION_FROM_PR" ]]; then
            echo "Version not found"
            exit 1
          fi
          if [[ -z "$TOP_TAG" ]]; then
            echo "No version found in CHANGELOG.md!"
            exit 1
          fi
          if [[ "$VERSION_FROM_PR" == "$TOP_TAG" || $(printf '%s\n%s' "$VERSION_FROM_PR" "$TOP_TAG" | sort -V | head -n1) != "$TOP_TAG" ]]; then
            echo "Invalid version provided"
            exit 1
          fi
          echo "Version is valid"
